### ISSUE TITLE
Consider using spglib_jll.jl as bin dep?

### ISSUE THREAD

**Issue by singularitti** [unkcpz/LibSymspg.jl#4]
JuliaBinaryWrappers now has `spglib_jll.jl` [`v1.15.1+0`](https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/tag/spglib-v1.15.1%2B0) published. And it is [compatible with Julia `v1.0`](https://github.com/JuliaBinaryWrappers/spglib_jll.jl/blob/347ce5ac4590e4290ec125c91ddefb428da26959/Project.toml#L10). So no need to worry about the version of Julia. And you do not have to build a bin dep yourself, they will do it. All you need to do is migration.

**Comment by unkcpz** [comment]
@singularitti thanks for your remind. But apology, I am no longer actively maintain this package. Could you make a PR or just fork and create it in your repository?

**Comment by singularitti** [comment]
I could, I will try. Thank you for what you have done!
